### Connected Components

In [1]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

In [2]:
arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

In [3]:
new_arr = csr_matrix(arr)

In [4]:
print(connected_components(new_arr))

(1, array([0, 0, 0]))


### Dijisktra

In [5]:
from scipy.sparse.csgraph import dijkstra

In [6]:
print(dijkstra(new_arr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


### Floyd Warshall

In [7]:
from scipy.sparse.csgraph import floyd_warshall

In [8]:
print(floyd_warshall(new_arr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


### Bellman Ford

In [9]:
from scipy.sparse.csgraph import bellman_ford

In [10]:
print(bellman_ford(new_arr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


### Depth first order

In [11]:
from scipy .sparse.csgraph import depth_first_order

In [12]:
print(depth_first_order(new_arr, 1))

(array([1, 0, 2]), array([    1, -9999,     0]))


### Breadth first order

In [13]:
from scipy.sparse.csgraph import breadth_first_order

In [14]:
print(breadth_first_order(new_arr, 1))

(array([1, 0, 2]), array([    1, -9999,     0]))
